url: http://127.0.01:8066

swagger_open: true

dev_fresh: 1

path:
  # log_folder: "/home/hxk/hade/log/"
  # runtime_folder: "/home/hxk/hade/runtime/"

#调试模式
dev: 
  port: 8070
  backend: 
    refresh_time: 3
    port: 8072
    monitor_folder: ""
  frontend: 
    port: 8071